[package]
name = "dy"
description = "Quickly generate a delightful, light, and human readable/writable syntax"
version = "0.0.1"
edition = "2021"
license-file = "LICENSE"

[dependencies]

[dev-dependencies]
ntest = "0.9.3"
pretty_assertions = "1.4.1"
