[workspace.package]
authors = ["Samuel Roland"]
edition = "2024"
license-file = "LICENSE"

[workspace.dependencies]
lsp-types = "0.97.0"
thiserror = "2.0.12"

[workspace]
members = ["crates/dy", "crates/plx"]
resolver = "2"
